# Basic Site Settings
#------------------------------------------------
title: Henna by Emma
description: 

# Theme
#------------------------------------------------
theme: jekyll-theme-cayman
show_downloads: false
google_analytics:

# Build Settings
#------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
