# Basic Site Settings
#------------------------------------------------
title: Emma's Henna
description: I like henna.
“The art of henna transcends borders and brings people from different cultures together in celebration. ”
— The Henna Artist by Alka Joshi

# Theme
#------------------------------------------------
theme: jekyll-theme-cayman
show_downloads: false
google_analytics:

# Build Settings
#------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
