# Basic Site Settings
#------------------------------------------------
title: Henna by Emma
description: Henna has been used for thousands of years across many cultures—as a natural dye, a blessing for weddings, a ritual of protection, and a way to celebrate beauty.
Whether you’re marking a special occasion or simply celebrating yourself, my goal is to make you feel adorned, radiant, and empowered through the timeless beauty of henna.

“The art of henna transcends borders and brings people from different cultures together in celebration. ”
— The Henna Artist by Alka Joshi

# Theme
#------------------------------------------------
theme: jekyll-theme-cayman
show_downloads: false
google_analytics:

# Build Settings
#------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
