# Basic Site Settings
#------------------------------------------------
title: Emma's Henna
description: I like henna.

# Theme
#------------------------------------------------
theme: jekyll-theme-cayman

# Build Settings
#------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
